apiVersion: apps/v1
kind: Deployment
metadata:
  name: giorgi-der-goat-fabo
  replicas: 11
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: gcr.io/google-samples/gb-frontend:v5
          name: giorgi-der-goat-fabo
          ports:
            - containerPort: 80
