apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-local
  namespace: guestbook-local
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-app-pod
  template:
    metadata:
      labels:
        app: guestbook-app-pod
    spec:
      containers:
        - image: gcr.io/google-samples/gb-frontend:v5
          name: guestbook
          ports:
            - containerPort: 80
